### ISSUE TITLE
CSS background images absolute path

### ISSUE THREAD

**Issue by stoimen** [nzakas/cssembed#12]
When background images are referenced with an absolute path i.e. background:url(/images/....) the applications appends this path to the path of the CSS file. If both are on the same level - /images and /styles the applications throws an error with ..../styles/images/.... file not found, actually it should be either .../images/... or ../styles/../images/...

**Comment by nzakas** [comment]
I'm assuming that this is because you didn't specify a base for the URLs, is that correct?

**Comment by stoimen** [comment]
I used the base path, but it didn't change the images path at all.

**Comment by nzakas** [comment]
Can you include a snippet of the CSS that was a problem? My testing with base seems to work. Thanks.

**Comment by stoimen** [comment]
Hi, everything is working just fine, as it appears I was missing some correct options setup. Thanks.

**Comment by nzakas** [comment]
No problem, thanks for the note!
