### ISSUE TITLE
Fixed Vista/IE7 bug (patch inside)

### ISSUE THREAD

**Issue by mashihua** [nzakas/cssembed#14]
Hi Nicholas.
Vista/IE7 bug can fixed with according to rfc2557 section 7. You can see example http://shihua.googlecode.com/svn/trunck/labs/2010/cssembed/index.html

Here is the patch I made:
http://shihua.googlecode.com/svn/trunck/labs/2010/cssembed/cssembed.patch

Hope the patch made this tools useful.

Best regards.

Shihua

**Comment by nzakas** [comment]
Hi, thanks for the patch. I'm a little confused, as it looks like this will produce an invalid CSS comment. Is the patch correct?

**Comment by mashihua** [comment]
Sorry for that patch missing two line.Now I update.

The mhtml which  in all example is :
/*
Content-Type: multipart/related; boundary="_SEPARATOR"

--_SEPARATOR
Content-Location:somestring
Content-Transfer-Encoding:base64

.......base64 data here......
*/

but in rfc2112 that format is:
/*
Content-Type: multipart/related; boundary="_SEPARATOR"

--_SEPARATOR
Content-Location:somestring
Content-Transfer-Encoding:base64

.......base64 data here......

--_SEPARATOR--
*/

The example2 show that example1 lose the closed boundary,In my example,if we write the example in css,it working correct in IE7@Vista with default settings.

Screen:
http://shihua.googlecode.com/svn/trunck/labs/2010/cssembed/screen.png

I personally think mayby the mhtml parser have normal model and strict model just like ecma5.

**Comment by nzakas** [comment]
Fixed in 0.3.3.
