### ISSUE TITLE
MHTML support (patch inside)

### ISSUE THREAD

**Issue by dchaplinsky** [nzakas/cssembed#3]
Hi Nicholas.

I've just added experimental support for the MHTML support for cssembed.

It's still very raw (it was my first java work and my editor even doesn't have syntax highlighting for Java), but it's already producing correct results.

Since code is junkie, I hope it at least will expose general idea, so we can make this tool even better.
Here is the link to the diff for changes I made:
http://pastebin.ca/1677046

Hope you will find it useful. 
Regards, 
Dmitry

**Comment by nzakas** [comment]
Hi Dmitry,

Thanks, you're the second person to request this (but the first to implement it!). I'll take a look this weekend.

**Comment by nzakas** [comment]
Added initial support for MHTML in 0.3.0 based on your patch. Right now, it's either MTHML or data URI, I'll look into allowing both at the same time in the future.

**Comment by dchaplinsky** [comment]
Great.
What do you think about exclude/include options for the tool?

It may be useful, if cssembed will be used in deploy chain.
