### ISSUE TITLE
Warnings about duplicate images (patch inside)

### ISSUE THREAD

**Issue by dchaplinsky** [nzakas/cssembed#4]
To avoid double (triple/n-ple) inclusion of the same image into the CSS, for example:
    #button1 {
        background: url(all-buttons-sprite.png) no-repeat 0 0;
        background-position: 0 0;
    }

```
#button2 {
    background: url(all-buttons-sprite.png) no-repeat 0 0;
    background-position: 0 -22px;
}
```

I made a simple patch which producing nice warnings when cssembed are running in verbose mode:
    [WARNING] Duplicate URL 'all-buttons-sprite.png' found at line 12, previously declared at line 7.

http://pastebin.ca/1682172

**Comment by nzakas** [comment]
Added in 0.2.7.
